package com.jimi.ozone_server.model;

import com.jimi.ozone_server.model.base.BaseGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Group extends BaseGroup<Group> {
	public static final Group dao = new Group().dao();
}
