package com.jimi.ozone_server.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("action_log", "id", ActionLog.class);
		arp.addMapping("group", "id", Group.class);
		arp.addMapping("pre_task", "id", PreTask.class);
		arp.addMapping("project", "id", Project.class);
		arp.addMapping("staff", "id", Staff.class);
		arp.addMapping("system_log", "id", SystemLog.class);
		arp.addMapping("task", "id", Task.class);
		arp.addMapping("task_schedule", "id", TaskSchedule.class);
		arp.addMapping("task_type", "id", TaskType.class);
	}
}

