package com.jimi.ozone_server.model;

import com.jimi.ozone_server.model.base.BasePreTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PreTask extends BasePreTask<PreTask> {
	public static final PreTask dao = new PreTask().dao();
}
