package com.jimi.ozone_server.model;

import com.jimi.ozone_server.model.base.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
	public static final Project dao = new Project().dao();
}
