package com.jimi.ozone_server.model;

import com.jimi.ozone_server.model.base.BaseStaff;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Staff extends BaseStaff<Staff> {
	public static final Staff dao = new Staff().dao();
}
