package com.jimi.ozone_server.model;

import com.jimi.ozone_server.model.base.BaseSystemLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemLog extends BaseSystemLog<SystemLog> {
	public static final SystemLog dao = new SystemLog().dao();
}
