package com.jimi.ozone_server.model;

import com.jimi.ozone_server.model.base.BaseTaskSchedule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskSchedule extends BaseTaskSchedule<TaskSchedule> {
	public static final TaskSchedule dao = new TaskSchedule().dao();
}
