package com.jimi.ozone_server.model;

import com.jimi.ozone_server.model.base.BaseTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Task extends BaseTask<Task> {
	public static final Task dao = new Task().dao();
}
