package com.jimi.ozone_server.model;

import com.jimi.ozone_server.model.base.BaseTaskType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskType extends BaseTaskType<TaskType> {
	public static final TaskType dao = new TaskType().dao();
}
