package com.jimi.ozone_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTaskSchedule<M extends BaseTaskSchedule<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setBeginTime(java.util.Date beginTime) {
		set("begin_time", beginTime);
		return (M)this;
	}
	
	public java.util.Date getBeginTime() {
		return get("begin_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
		return (M)this;
	}
	
	public java.util.Date getFinishTime() {
		return get("finish_time");
	}

	public M setStaffId(java.lang.Long staffId) {
		set("staff_id", staffId);
		return (M)this;
	}
	
	public java.lang.Long getStaffId() {
		return getLong("staff_id");
	}

	public M setTaskId(java.lang.Long taskId) {
		set("task_id", taskId);
		return (M)this;
	}
	
	public java.lang.Long getTaskId() {
		return getLong("task_id");
	}

	public M setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}

	public M setProjectId(java.lang.Long projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Long getProjectId() {
		return getLong("project_id");
	}

}
