package com.jimi.ozone_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePreTask<M extends BasePreTask<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTaskId(java.lang.Long taskId) {
		set("task_id", taskId);
		return (M)this;
	}
	
	public java.lang.Long getTaskId() {
		return getLong("task_id");
	}

	public M setPreTask(java.lang.Long preTask) {
		set("pre_task", preTask);
		return (M)this;
	}
	
	public java.lang.Long getPreTask() {
		return getLong("pre_task");
	}

	public M setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}

}
