package com.jimi.ozone_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProject<M extends BaseProject<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setBeginTime(java.util.Date beginTime) {
		set("begin_time", beginTime);
		return (M)this;
	}
	
	public java.util.Date getBeginTime() {
		return get("begin_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setManager(java.lang.Long manager) {
		set("manager", manager);
		return (M)this;
	}
	
	public java.lang.Long getManager() {
		return getLong("manager");
	}

	public M setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}

}
